package com.github.superzhc.web.mapper;

import com.github.superzhc.web.model.Onetab;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface OnetabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onetab
     *
     * @mbg.generated Sat Sep 05 14:32:51 CST 2020
     */
    @Delete({
        "delete from onetab",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onetab
     *
     * @mbg.generated Sat Sep 05 14:32:51 CST 2020
     */
    @Insert({
        "insert into onetab (id, url, ",
        "title, level, readed)",
        "values (#{id,jdbcType=INTEGER}, #{url,jdbcType=VARCHAR}, ",
        "#{title,jdbcType=VARCHAR}, #{level,jdbcType=INTEGER}, #{readed,jdbcType=INTEGER})"
    })
    int insert(Onetab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onetab
     *
     * @mbg.generated Sat Sep 05 14:32:51 CST 2020
     */
    @Select({
        "select",
        "id, url, title, level, readed",
        "from onetab",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="level", property="level", jdbcType=JdbcType.INTEGER),
        @Result(column="readed", property="readed", jdbcType=JdbcType.INTEGER)
    })
    Onetab selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onetab
     *
     * @mbg.generated Sat Sep 05 14:32:51 CST 2020
     */
    @Select({
        "select",
        "id, url, title, level, readed",
        "from onetab"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="level", property="level", jdbcType=JdbcType.INTEGER),
        @Result(column="readed", property="readed", jdbcType=JdbcType.INTEGER)
    })
    List<Onetab> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onetab
     *
     * @mbg.generated Sat Sep 05 14:32:51 CST 2020
     */
    @Update({
        "update onetab",
        "set url = #{url,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "level = #{level,jdbcType=INTEGER},",
          "readed = #{readed,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Onetab record);

    @Select({
            "select",
            "id, url, title, level, readed",
            "from onetab",
            "where url = #{url,jdbcType=VARCHAR}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
            @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
            @Result(column="level", property="level", jdbcType=JdbcType.INTEGER),
            @Result(column="readed", property="readed", jdbcType=JdbcType.INTEGER)
    })
    Onetab selectByUrl(String url);

    @Select({
            "<script>",
            "select",
            "id, url, title, level, readed",
            "from onetab",
            "<where>",
                "<if test=\"title!=null and title!=''\">" ,
                    "and title like concat('%', #{title}, '%')" ,
                "</if>",
            "</where>",
            "</script>"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
            @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
            @Result(column="level", property="level", jdbcType=JdbcType.INTEGER),
            @Result(column="readed", property="readed", jdbcType=JdbcType.INTEGER)
    })
    List<Onetab> selectByCondition(Map params);
}
