package com.github.superzhc.web.model;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookId
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    private String bookid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.fullname
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    private String fullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.name
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.visiturl
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    private String visiturl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.size
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.categoryname
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    private String categoryname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.updateDate
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    private String updatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.baidu
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    private String baidu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.address
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookId
     *
     * @return the value of book.bookId
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    public String getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookId
     *
     * @param bookid the value for book.bookId
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    public void setBookid(String bookid) {
        this.bookid = bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.fullname
     *
     * @return the value of book.fullname
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.fullname
     *
     * @param fullname the value for book.fullname
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.name
     *
     * @return the value of book.name
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.name
     *
     * @param name the value for book.name
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.visiturl
     *
     * @return the value of book.visiturl
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    public String getVisiturl() {
        return visiturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.visiturl
     *
     * @param visiturl the value for book.visiturl
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    public void setVisiturl(String visiturl) {
        this.visiturl = visiturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.size
     *
     * @return the value of book.size
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.size
     *
     * @param size the value for book.size
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    public void setSize(String size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.categoryname
     *
     * @return the value of book.categoryname
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    public String getCategoryname() {
        return categoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.categoryname
     *
     * @param categoryname the value for book.categoryname
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.updateDate
     *
     * @return the value of book.updateDate
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    public String getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.updateDate
     *
     * @param updatedate the value for book.updateDate
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    public void setUpdatedate(String updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.baidu
     *
     * @return the value of book.baidu
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    public String getBaidu() {
        return baidu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.baidu
     *
     * @param baidu the value for book.baidu
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    public void setBaidu(String baidu) {
        this.baidu = baidu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.address
     *
     * @return the value of book.address
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.address
     *
     * @param address the value for book.address
     *
     * @mbg.generated Sun Sep 06 01:30:09 CST 2020
     */
    public void setAddress(String address) {
        this.address = address;
    }
}