package com.github.superzhc.web.model;

public class KafkaCluster {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kafka_cluster.id
     *
     * @mbg.generated Tue Sep 08 00:24:05 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kafka_cluster.url
     *
     * @mbg.generated Tue Sep 08 00:24:05 CST 2020
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kafka_cluster.id
     *
     * @return the value of kafka_cluster.id
     *
     * @mbg.generated Tue Sep 08 00:24:05 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kafka_cluster.id
     *
     * @param id the value for kafka_cluster.id
     *
     * @mbg.generated Tue Sep 08 00:24:05 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kafka_cluster.url
     *
     * @return the value of kafka_cluster.url
     *
     * @mbg.generated Tue Sep 08 00:24:05 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kafka_cluster.url
     *
     * @param url the value for kafka_cluster.url
     *
     * @mbg.generated Tue Sep 08 00:24:05 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }
}