package com.github.superzhc.web.model;

public class Onetab {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onetab.id
     *
     * @mbg.generated Sat Sep 05 14:32:51 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onetab.url
     *
     * @mbg.generated Sat Sep 05 14:32:51 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onetab.title
     *
     * @mbg.generated Sat Sep 05 14:32:51 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onetab.level
     *
     * @mbg.generated Sat Sep 05 14:32:51 CST 2020
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onetab.readed
     *
     * @mbg.generated Sat Sep 05 14:32:51 CST 2020
     */
    private Integer readed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onetab.id
     *
     * @return the value of onetab.id
     *
     * @mbg.generated Sat Sep 05 14:32:51 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onetab.id
     *
     * @param id the value for onetab.id
     *
     * @mbg.generated Sat Sep 05 14:32:51 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onetab.url
     *
     * @return the value of onetab.url
     *
     * @mbg.generated Sat Sep 05 14:32:51 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onetab.url
     *
     * @param url the value for onetab.url
     *
     * @mbg.generated Sat Sep 05 14:32:51 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onetab.title
     *
     * @return the value of onetab.title
     *
     * @mbg.generated Sat Sep 05 14:32:51 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onetab.title
     *
     * @param title the value for onetab.title
     *
     * @mbg.generated Sat Sep 05 14:32:51 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onetab.level
     *
     * @return the value of onetab.level
     *
     * @mbg.generated Sat Sep 05 14:32:51 CST 2020
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onetab.level
     *
     * @param level the value for onetab.level
     *
     * @mbg.generated Sat Sep 05 14:32:51 CST 2020
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onetab.readed
     *
     * @return the value of onetab.readed
     *
     * @mbg.generated Sat Sep 05 14:32:51 CST 2020
     */
    public Integer getReaded() {
        return readed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onetab.readed
     *
     * @param readed the value for onetab.readed
     *
     * @mbg.generated Sat Sep 05 14:32:51 CST 2020
     */
    public void setReaded(Integer readed) {
        this.readed = readed;
    }
}